{
 "title": "{{component}}",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "com;ponent process",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"{{env}}-{{component}}\",exported_name=\"{{service_name}}.service\",state=\"active\"}"
    }
   ]
  },
  {
   "title": "cpu time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (name)(floor(rate(node_cpu_seconds_total{ mode=\"idle\", name=\"{{env}}-{{component}}\"}[1m]) * 100)))"
    }
   ]
  },
  {
   "title": "cpu  %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (name)(floor(rate(node_cpu_seconds_total{ mode=\"idle\", name=\"{{env}}-{{component}}\"}[1m]) * 100)))"
    }
   ]
  },
  {
   "title": "memory used percentage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_memory_used_percent{name=\"{{env}}-{{component}}\"}"
    }
   ]
  }
 ]
}