- name: configuring yum repos
  ansible.builtin.shell: curl -s {{item}} | bash
  loop:
    - curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh
    - curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh

- name: install erlang and rabbitmq
  ansible.builtin.yum:
    name:
      - rabbitmq-server
    state: installed

- name: start rabbitmq server
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: add application user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: "{{roboshop_rabbitmq_password}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: administrator
  vars:
    roboshop_rabbitmq_password: "{{ lookup('aws_ssm', '{{env}}.{{component}}.AMQP_PASS', region='us-east-1' ) }}"


