- name: configure nodejs
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: add apllication user
  ansible.builtin.user:
    name: roboshop

- name: remove old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download catalogue content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
    dest: /app
    remote_src: yes

- name: install nodejs depandencies
  community.general.npm:
    path: /app
    state: latest

- name: copy systemd file
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: start catalogue service
  ansible.builtin.systemd:
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: copy mongodb repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install mongodb
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: load schema
  community.mongodb.mongodb-shell:
    login_host: mongodb-dev.anandnandhu.online
    file: "/app/schema/catalogue.js"
    idempotent: yes